# -*- coding: utf-8 -*-
"""menu.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15cHKGbt7ZnG5pJSXsBLzCYVGsWDHToBZ
"""

class menu():
    def __init__(self,name,description):
        self.name=name
        self.description=description
class veg_pizza(menu):
    def __init__(self,name,description,small_price,medium_price,large_price):
        super().__init__(name,description)
        self.small_price=small_price
        self.medium_price=medium_price
        self.large_price=large_price
class classic(veg_pizza):
    def __init__(self,name,description,small_price,medium_price,large_price):
        super().__init__(name,description,small_price,medium_price,large_price)
    def margherita(self):
        print(f'Classic veg\n\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
class simply_veg(veg_pizza):
    def veggie_lover(self):
        print(f'simply veg \n\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def country_fest(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def double_cheese_margherita(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')

class supreme_veg(veg_pizza):
    def farm_house(self):
        print(f'suprme veg \n\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def itallian_celebration(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def mexican_treat(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')

class non_veg_pizza(menu):
    def __init__(self,name,description,small_price,medium_price,large_price):
        super().__init__(name,description)
        self.small_price=small_price
        self.medium_price=medium_price
        self.large_price=large_price
class simply_non_veg(non_veg_pizza):
    def chicken_salami(self):
        print(f'simply non veg \n\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def lajawab_seekh_kabab(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
class non_veg_supreme(non_veg_pizza):
    def chicken_supreme_triple_tango(self):
        print(f'non_veg_supreme \n\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def hawain_pizza(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
    def maxican_pizza(self):
        print(f'\t\t* {self.name} ( {self.description} ) \n\t\t small  {self.small_price} \n\t\t medium {self.medium_price} \n\t\t large {self.large_price} ')
class burger():
    def __init__(self,type):
        self.type=type
        print(f'{self.type}')
class veg_burger(burger):
    def classic_crunchy(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def aloo_tikki(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def veg_patty(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def cheese_burger(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def spicy_paneer_burger(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def veg_maharaja_burger(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
class non_veg_burger(burger):
    def chicken_patty(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def fried_chicken(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')
    def non_veg_maharaja_burger(self,name,price):
        self.name=name
        self.price=price
        print(f'\t\t{self.name} = {self.price}')

        print('free coke on orders above 149')

classic=classic('margherita','single cheese toping',105,180,250)
classic.margherita()
y=simply_veg('veggie lover','onion, capisicum',115,195,265)
y.veggie_lover()
x=simply_veg('country_fest','onion, tomato and capisicum',115,195,265)
x.country_fest()
a=simply_veg('double cheese margherita','extra cheese on cheese',115,195,265)
a.double_cheese_margherita()
q=supreme_veg('farm house','onion,capsicum,tomato & mushroom',135,225,295)
q.farm_house()
w=supreme_veg('itallian celebration','black olives,jalapenos & sweet corn',135,225,295)
w.itallian_celebration()
e=supreme_veg('mexican treat','onion,capisicum',135,225,295)
e.mexican_treat()
r=simply_non_veg('chicken salami','onion,capisicum & chicken salami',140,240,335)
r.chicken_salami()
t=simply_non_veg('lajawab seekh kabab','onion,capsicum & seekh kabab',140,240,335)
t.lajawab_seekh_kabab()
y=non_veg_supreme('chicken supreme triple tango','chicken kheema,seekh kabab,chicken salami & spices',185,275,360)
y.chicken_supreme_triple_tango()
u=non_veg_supreme('hawain pizza','mashroom,jalapenos,black oliver & hot chicken',185,275,360)
u.hawain_pizza()
i=non_veg_supreme('maxican pizza','onion,capsicum,chicken salami & hot chicken',185,275,360)
i.maxican_pizza()
o=veg_burger('veg burger')
o.classic_crunchy('classic crunchy',39)
o.aloo_tikki('aloo tikki',49)
o.veg_patty('veg patty',59)
o.cheese_burger('cheese burger',79)
o.spicy_paneer_burger('spicy paneer burger',129)
o.veg_maharaja_burger('veg maharaja burger',169)
p=non_veg_burger('non veg burger')
p.chicken_patty('chicken patty burger',89)
p.fried_chicken('fried chicken burger',99)
p.non_veg_maharaja_burger('fried chicken burger',99)